name: my_portfolio_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Icons for iOS
  cupertino_icons: ^1.0.8

  # Networking
  http: ^1.2.0

  # Opening Links (WhatsApp, GitHub, etc.)
  url_launcher: ^6.2.0

  # Custom Fonts (Fraktur, Neon effects)
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# --- FLUTTER CONFIGURATION ---
flutter:
  uses-material-design: true

  # 1. REGISTER YOUR ASSETS HERE
  # Make sure you created a folder named 'assets' in your project root
  # and put 'profile.png' inside it.
  assets:
    - assets/profile.png
